# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
