# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-08 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_workshop', '0002_auto_20170708_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatus',
            name='slug',
        ),
    ]
