# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-08 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_workshop', '0003_remove_jobstatus_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mark',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='related_tasks', to='car_workshop.Mark'),
        ),
    ]
