# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-08 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_workshop', '0004_task_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['mark']},
        ),
    ]
