# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-27 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_workshop', '0008_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
    ]
