# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_workshop', '0009_remove_task_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='model_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='mark_name',
            new_name='name',
        ),
    ]
