# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_workshop', '0011_auto_20171025_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.CharField(max_length=9),
        ),
    ]
