# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_workshop', '0012_auto_20171026_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
